services:
  - type: web
    name: AI-Research-Newsletter-Generator
    runtime: python
    buildCommand: pip install --upgrade pip && pip install tiktoken==0.9.0 --prefer-binary && pip install --prefer-binary -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: src
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false   # add manually in dashboard
      - key: SERPER_API_KEY
        sync: false
      - key: MODEL
        value: gemini/gemini-2.5-flash-lite
      - key: CREWAI_TELEMETRY_OPT_OUT
        value: "true"