services:
  - type: web
    name: AI-Research-Newsletter-Generator
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONPATH
        value: src
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false   # add manually in dashboard
      - key: SERPER_API_KEY
        sync: false
      - key: MODEL
        value: gemini/gemini-2.5-flash-lite
      - key: CREWAI_TELEMETRY_OPT_OUT
        value: "true"